seed: 5555
model:
  mid_channel: 196
  expand: [2.25, 1.75, 1.25]
  neck: 
    type: RFB_Lite
  Edge_Ass:
    using: True
    mid_channel: 4
    using_PV: False
    inchannel: 3
    using_edge_SC: True
    PV_reduction: None
    PV_normal: True
    gain: 1.0
  header: my_aggregation_lite_CSP
  PQ:
    using: True
    patch_size: 4
    map_size: 16
    num_head: 8
    type: prior_query2_channel_last_L_attention_rm_SA.prior_query
    using_pretrain: True
    pretrain_path: models/pretrained/prior_query2_channel_last_L_attention_rm_SA/pretrain/model_199.pth
    position: [True,True,True]

  

loss:
  combination: ['DICE','SSIM', 'FocalLoss','MSELoss','WBCE','Contrast_Loss','Contrast_Loss','Contrast_Loss','Contrast_Loss']
  using_Deepest_loss: True
  combination_p: [[],[],[2],[],[],[0.95],[0.8],[0.65],[0.5]]
  loss_weight: [0.0625,   0.125,0.125,   0.25,0.25,0.25,   0.5,0.5,0.5,   0.5,0] #sum(combination)+edge_loss
  loss_scale:
    number: 4   #11,22,44
    combination: [[1],[1,2],[1,2,3],[1,2,3]]
  edge:
    using: True
    gamma: 1.5
    gains: [1,48,64]
    weights: [1, 0.25, 0.0625] #1,1/4,1/16
    stage: [10,20,40]
    max_rate: 0.9
    base_size: 288
    loss_type: bce
  using_normal: True


dataloader:
  batch_size: 12

solver:
  init_epoch: 10
  epoch: 70
  lr_rate: [0.1,1.5,1]
  decay_rate: 1.0
  lr_step: [10,30,70]